server:
  port: 3001
  readTimeout: 30
  writeTimeout: 30
  queueSize: 100
  concurrency: 5

nodes:
  - name: "MAC_STUDIO"
    host: "192.168.68.143"
    port: 3000
    type: "gpu"
    platform: "macos"
    capabilities: ["tensor", "metal"]
  - name: "MAC_MINI"
    host: "192.168.68.136"
    port: 3000
    type: "gpu"
    platform: "macos"
    capabilities: ["tensor", "metal"]
  - name: "MAC_BOOK_PRO"
    host: "192.168.68.165"
    port: 3000
    type: "gpu"
    platform: "macos"
    capabilities: [ "tensor", "metal" ]
  - name: "BLACK_PRIME"
    host: "192.168.68.135"
    port: 3000
    type: "cpu"
    platform: "windows"
    capabilities: ["avx512", "parallel"]
  - name: "BlackHP"
    host: "localhost"
    port: 3000
    type: "cpu"
    platform: "windows"
    capabilities: ["avx512", "parallel"]
