server:
  port: 3001
  readTimeout: 30
  writeTimeout: 30
  queueSize: 100
  concurrency: 20

mongodb:
  uri: "mongodb://192.168.68.145:27017/logs"
  database: "logs"

nodes:
  - name: "MAC_STUDIO"
    host: "localhost"
    port: 3000
    type: "gpu"
    platform: "macos"
    capabilities: ["tensor", "metal"]
  - name: "MAC_MINI"
    host: "192.168.68.110"
    port: 3000
    type: "gpu"
    platform: "macos"
    capabilities: ["tensor", "metal"]
  - name: "MAC_BOOK_PRO"
    host: "192.168.68.165"
    port: 3000
    type: "gpu"
    platform: "macos"
    capabilities: [ "tensor", "metal" ]
  - name: "BLACK_PRIME"
    host: "192.168.68.135"
    port: 3000
    type: "cpu"
    platform: "windows"
    capabilities: ["avx512", "parallel"]
  - name: "BlackHP"
    host: "192.168.68.145"
    port: 3000
    type: "cpu"
    platform: "windows"
    capabilities: ["avx512", "parallel"]
  - name: "BlackPicollo"
    host: "192.168.68.152"
    port: 3000
    type: "cpu"
    platform: "windows"
    capabilities: [ "avx512", "parallel" ]
  - name: "ZBOOK"
    host: "192.168.68.177"
    port: 3000
    type: "cpu"
    platform: "windows"
    capabilities: [ "avx512", "parallel" ]
